### ISSUE TITLE
Build gallery of inspirations

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_interactive_streets_tiles#9]
Other killer interactive web maps

**Comment by jwrcoleman** [comment]
I'm suggesting we put this in the wiki for now, and potentially a pinned google doc in the resources channel on slack?. I'd like to see links to good web maps together on commentary on:
1) what platforms/technologies are used
2) what elements we like (e.g. it could be as little as the date slider used in this map is great)

**Comment by q-schen** [comment]
We now have a [Pinterest account](https://www.pinterest.ca/terrestrialwherever/)! Currently playing with it to see if it fits our hopes and dreams :)

**Comment by q-schen** [comment]
[Pinterest Tutorial.docx](https://github.com/CityofToronto/bdit_interactive_streets_tiles/files/1419743/Pinterest.Tutorial.docx)
